<?php
/*
    This file is part of the eQual framework <http://www.github.com/equalframework/equal>
    Some Rights Reserved, eQual framework, 2010-2026
    Original author(s): Cédric FRANCOYS
    License: GNU LGPL 3 license <http://www.gnu.org/licenses/>
*/
namespace equal\db;

use equal\organic\Service;

/**
 * Service for connecting to the DBMS holding the database of the current installation.
 * This service acts as a facade for DB interactions.
 *
 * List of methods forwarded to the active DBManipulator through `__call()`:
 * @method void addMember(DBManipulator $member) Add a replica member.
 * @method mixed select(string $db_name) Select a database.
 * @method bool connected() Check whether a database connection is active.
 * @method string getSqlType(string $type) Get the SQL type matching an ORM type.
 * @method bool canConnect() Check whether the database server is reachable.
 * @method mixed sendQuery(string $query) Send an SQL query to the database.
 * @method bool isEmpty(mixed $value) Check whether a value is considered empty by the database layer.
 * @method mixed getLastId() Get the identifier generated by the latest insert query.
 * @method int getAffectedRows() Get the number of rows affected by the latest query.
 * @method string getLastQuery() Get the latest executed query.
 * @method mixed fetchRow(mixed $result) Fetch the next row from a query result as an indexed array.
 * @method mixed fetchArray(mixed $result) Fetch the next row from a query result as an associative array.
 * @method string getCompositeIndexName(array $columns) Get the index name for a list of columns.
 * @method mixed getRecords($tables, $fields=null, $ids=null, $conditions=null, string $id_field='id', $order=[], int $start=0, int $limit=0) Read records.
 * @method mixed setRecords(string $table, $ids, array $fields, $conditions=null, string $id_field='id') Update records.
 * @method mixed addRecords(string $table, array $fields, array $values) Insert records.
 * @method mixed deleteRecords(string $table, $ids, $conditions=null, string $id_field='id') Delete records.
 * @method mixed incRecords(string $table, $ids, string $field, $increment, string $id_field='id') Increment a field and return its previous values.
 * @method void createDatabase(string $db_name) Create a database.
 * @method string[] getTables() Get the names of all database tables.
 * @method array getTableSchema(string $table_name) Get a table schema.
 * @method string[] getTableColumns(string $table_name) Get the names of a table's columns.
 * @method string[] getTableUniqueConstraints(string $table_name) Get a table's unique constraints.
 * @method string getQueryCreateTable(string $table_name) Build a table creation query.
 * @method string getQueryAddColumn(string $table_name, string $column_name, array $def) Build a column creation query.
 * @method string getQueryAddIndex(string $table_name, string $column) Build an index creation query.
 * @method string getQueryAddCompositeIndex(string $table_name, array $columns) Build a composite index creation query.
 * @method string getQueryAddUniqueConstraint(string $table_name, $columns) Build a unique constraint creation query.
 * @method string getQueryAddRecords(string $table, array $fields, array $values) Build a records insertion query.
 * @method string getQuerySetRecords(string $table, array $fields) Build a records update query.
 */
class DBConnector extends Service {

    /** @var DBManipulator */
    private $connection;

    public static function constants() {
        return ['DB_DBMS', 'DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_CHARSET', 'DB_COLLATION'];
    }

    protected function __construct() {
        $this->connection = DBConnection::create(
                constant('DB_DBMS'),
                constant('DB_HOST'),
                constant('DB_PORT'),
                constant('DB_NAME'),
                constant('DB_USER'),
                constant('DB_PASSWORD'),
                constant('DB_CHARSET'),
                constant('DB_COLLATION')
            );

        if(defined('DB_REPLICATION') && constant('DB_REPLICATION') != 'NO') {
            // add replica members, if any
            $i = 1;

            while(defined('DB_'.$i.'_HOST')
                && defined('DB_'.$i.'_PORT')
                && defined('DB_'.$i.'_USER')
                && defined('DB_'.$i.'_PASSWORD')
                && defined('DB_'.$i.'_NAME')) {

                $this->addReplicaMember(
                    constant('DB_'.$i.'_HOST'),
                    constant('DB_'.$i.'_PORT'),
                    constant('DB_'.$i.'_NAME'),
                    constant('DB_'.$i.'_USER'),
                    constant('DB_'.$i.'_PASSWORD')
                );
                ++$i;
            }
        }
    }

    public function addReplicaMember($host, $port, $db, $user, $pass) {
        /** @var DBManipulator */
        $member = DBConnection::create(constant('DB_DBMS'), $host, $port, $db, $user, $pass);
        if($member && $this->connection) {
            $this->connection->addMember($member);
        }
    }

    /**
     * Open the DBMS connection.
     *
     * @param bool $auto_select Whether to select the configured database automatically.
     * @return DBManipulator|false The active DB manipulator on success, or false on failure.
     */
    public function connect($auto_select=true) {
        return isset($this->connection) ? $this->connection->connect($auto_select) : false;
    }

    public function disconnect() {
        return !isset($this->connection) || $this->connection->disconnect();
    }

    /**
     * Magic overloading method: catch any call and relay it to DBManipulator object
     *
     * @param  string                 $name
     * @param  array                  $arguments
     * @return mixed
     */
    public function __call($name, $arguments) {
        if (!$this->connection) {
            return null;
        }
        return call_user_func_array([$this->connection, $name], $arguments);
    }

}
