<?php
/*
    This file is part of the eQual framework <http://www.github.com/equalframework/equal>
    Some Rights Reserved, eQual framework, 2010-2026
    Original author(s): Cédric FRANCOYS
    Licensed under GNU LGPL 3 license <http://www.gnu.org/licenses/>
*/
namespace equal\db;

/**
 * Base class defining the shared state and API implemented by DBMS-specific manipulators.
 *
 * This class is not intended to be instantiated directly.
 */
class DBManipulator {

    /**
     * DB server hostname.
     *
     * @var		string
     */
    protected $host;

    /**
     * DB server TCP connection port.
     *
     * @var		int|null
     */
    protected $port;

    /**
     * DB name to use for SQL queries.
     *
     * @var		string
     */
    protected $db_name;

    /**
     * Charset encoding to use for communications with DBMS.
     *
     * @var		string|null
     */
    protected $charset;

    /**
     * Collation to use for storing data (applied on new tables and columns).
     *
     * @var		string|null
     */
    protected $collation;

    /**
     * DB user
     *
     * @var		string
     */
    protected $user_name;

    /**
     * DB password
     *
     * @var		string
     */
    protected $password;

    /**
     * Identifier generated by the latest insert query.
     *
     * @var		int|string|null
     */
    protected $last_id;

    /**
     * Number of rows affected by last query
     *
     * @var		int|false|null
     */
    protected $affected_rows;

    /**
     * Latest query
     *
     * @var		string|null
     */
    protected $last_query;

    /**
     * @var     mixed
     */
    protected $dbms_handler;

    /**
     * Secondary DBMS manipulators used as replication members, if any.
     *
     * @var		DBManipulator[]
     * @access	protected
     */
    protected $members;


    /**
     * Class constructor
     *
     * Initialize the DBMS data for SQL transactions
     *
     * @access   public
     * @param    string      $host       DB server hostname.
     * @param    int|null    $port       DB server TCP connection port.
     * @param    string      $db         Database name.
     * @param    string      $user       Username to use for the connection.
     * @param    string      $pass       Password to use for the connection.
     * @param    string|null $charset    Charset used for communications with the DBMS.
     * @param    string|null $collation  Collation used for newly created tables and columns.
     * @return   void
     */
    public final function __construct($host, $port, $db, $user, $pass, $charset=null, $collation=null) {
        $this->host         = $host;
        $this->port         = $port;
        $this->db_name      = $db;
        $this->user_name    = $user;
        $this->password     = $pass;
        $this->charset      = $charset;
        $this->collation    = $collation;

        $this->dbms_handler = null;
        $this->members      = [];
    }


    public final function __destruct() {
        $this->disconnect();
    }

    /**
     * Add a replication member.
     *
     * @param DBManipulator $member Manipulator connected to a secondary DBMS.
     * @return void
     */
    public function addMember(DBManipulator $member) {
        $this->members[] = $member;
    }

    /**
     * Open the DBMS connection.
     *
     * @param bool $auto_select Whether to select the configured database automatically.
     * @return DBManipulator|false The active manipulator on success, or false on failure.
     * @access   public
     */
    public function connect($auto_select=true) {
        return $this;
    }

    /**
     * Select a database on the active DBMS connection.
     *
     * @param string $db_name Database name.
     * @return mixed Driver-specific selection status or connection handler.
     */
    public function select($db_name) {
    }

    /**
     * Check whether a DBMS connection is active.
     *
     * @return bool
     */
    public function connected() {
        return (bool) $this->dbms_handler;
    }

    /**
     * Close the DBMS connection.
     *
     * @return bool True when the connection is closed or was already closed.
     * @access public
     */
    public function disconnect() {
    }

    /**
     * Returns the SQL type to use for a given ORM type.
     * This method is meant to be overloaded in children DBManipulator classes.
     *
     * @param string $type ORM type.
     * @return string Matching SQL type, or an empty string when no mapping exists.
     * @deprecated - use DataAdapterProviderSql::get(<usage>)
     */
    public function getSqlType($type) {
        return '';
    }

    /**
     * Checks the connectivity to an SQL server.
     *
     * @return bool False if no connection can be made, true otherwise.
     */
    public function canConnect() {
        if($fp = fsockopen($this->host, $this->port, $errno, $errstr, 1)) {
            fclose($fp);
            return true;
        }
        return false;
    }

    /**
     * Sends a SQL query.
     *
     * @param string $query The query to send to the DBMS.
     *
     * @return mixed Driver-specific query result, or null when the query is empty.
     * @throws \Exception If the query cannot be executed.
     */
    public function sendQuery($query) {
	}

    /**
     * Check whether a value is considered empty by the database layer.
     *
     * @param mixed $value Value to inspect.
     * @return bool
     */
    public final function isEmpty($value) {
        return (empty($value) || $value == '0000-00-00' || !strcasecmp($value, 'false') || !strcasecmp($value, 'null'));
    }

    /**
     * Get the identifier generated by the latest insert query.
     *
     * @return int|string|null
     */
    public function getLastId() {
        return $this->last_id;
    }

    /**
     * Get the number of rows affected by the latest query.
     *
     * @return int|false|null
     */
    public function getAffectedRows() {
        return $this->affected_rows;
    }

    /**
     * Get the latest executed query.
     *
     * @return string|null
     */
    public function getLastQuery() {
        return $this->last_query;
    }

    /**
     * Fetch the next row from a driver-specific query result.
     *
     * @param mixed $result Driver-specific query result.
     * @return array|bool|null An indexed row when supported, or a driver-specific iteration status.
     */
    public static function fetchRow($result) {
        return [];
    }

    /**
     * Fetch the next row as an associative array.
     *
     * @param mixed $result Driver-specific query result.
     * @return array|false|null The row, or a value indicating that no row is available.
     */
    public static function fetchArray($result) {
        return [];
    }

    /**
     * Store the identifier generated by the latest insert query.
     *
     * @param int|string|null $id Generated identifier.
     * @return void
     */
    protected function setLastId($id) {
        $this->last_id = $id;
    }

    /**
     * Store the number of rows affected by the latest query.
     *
     * @param int|false|null $affected_rows Number of affected rows.
     * @return void
     */
    protected function setAffectedRows($affected_rows) {
        $this->affected_rows = $affected_rows;
    }

    /**
     * Store the latest executed query.
     *
     * @param string|null $query SQL query.
     * @return void
     */
    protected function setLastQuery($query) {
        $this->last_query = $query;
    }

    /**
     * Get a deterministic index name for a list of columns.
     *
     * @param string[]|null $columns Column names.
     * @return string
     */
    public function getCompositeIndexName($columns) {
        $index_name = 'idx_' . implode('_', $columns ?? []);
        // #todo - use global constant - to adapt depending on DBMS and/or version
        $MAX_LEN = 64;
        // prevent index name size overflow
        if(strlen($index_name) > $MAX_LEN) {
            $index_name = 'idx_' . md5($index_name);
        }
        return $index_name;
    }

    /**
     * Get records from specified table, according to some conditions.
     *
     * @param array|string          $tables      Name or map of involved tables.
     * @param array|string|null     $fields      Requested field or fields.
     * @param array|int|string|null $ids         Identifiers to which the selection is limited.
     * @param array|null            $conditions  List of conditions expressed as field, operand and value tuples.
     * @param string                $id_field    Name of the identifier field (`id` by default).
     * @param array|string          $order       Order field, or map of field names to sorting directions.
     * @param int                   $start       Zero-based result offset.
     * @param int                   $limit       Maximum number of records, or zero for no limit.
     *
     * @return mixed Driver-specific query result.
     * @throws \Exception If the query cannot be built or executed.
     */
    public function getRecords($tables, $fields=NULL, $ids=NULL, $conditions=NULL, $id_field='id', $order=[], $start=0, $limit=0) {}

    /**
     * Update records in a table according to identifiers or conditions.
     *
     * @param string                $table       Table name.
     * @param array|int|string|null $ids         Identifiers to update.
     * @param array                 $fields      Map of column names to their new values.
     * @param array|null            $conditions  Additional update conditions.
     * @param string                $id_field    Name of the identifier field (`id` by default).
     * @return mixed Driver-specific query result.
     */
    public function setRecords($table, $ids, $fields, $conditions=null, $id_field='id') {}

    /**
     * Inserts new records in specified table.
     *
     * @param string $table  Name of the table in which to insert the records.
     * @param array  $fields List of involved fields.
     * @param array  $values Rows of values corresponding to the specified fields.
     * @return mixed Driver-specific query result.
     */
    public function addRecords($table, $fields, $values) {}

    /**
     * Delete records from a table according to identifiers or conditions.
     *
     * @param string                $table       Table name.
     * @param array|int|string|null $ids         Identifiers to delete.
     * @param array|null            $conditions  Additional deletion conditions.
     * @param string                $id_field    Name of the identifier field (`id` by default).
     * @return mixed Driver-specific query result.
     */
    public function deleteRecords($table, $ids, $conditions=null, $id_field='id') {}

    /**
     * Fetch and increment the column of a series of records in a single operation.
     * This method implements FAA instruction (fetch-and-add) in order to read and update a column as an atomic operation.
     *
     * @param string           $table      Table name.
     * @param array|int|string $ids        Identifiers of the records to update.
     * @param string           $field      Name of the numeric column to update.
     * @param int|float        $increment  Value to add, or to subtract when negative.
     * @param string           $id_field   Name of the identifier field (`id` by default).
     * @return mixed Driver-specific query result containing the values before the increment.
     */
    public function incRecords($table, $ids, $field, $increment, $id_field='id') {}


    /*
        SQL request generation helpers
    */


    /**
     * Creates a new database.
     *
     * Executes the DBMS-specific operation required to create the given database.
     *
     * @param string $db_name   The name of the database to create.
     * @return void
     */
    public function createDatabase($db_name) {}

    /**
     * Retrieves the list of all tables from the current database.
     *
     * @return string[] Names of all database tables.
     */
    public function getTables() {}

    /**
     * Retrieves the schema of the specified table.
     *
     * @param string $table_name    The name of the table whose schema is to be retrieved.
     * @return array<string, array{type: mixed, collation: mixed, nullable: mixed, default: mixed}> Table schema indexed by column name.
     */
    public function getTableSchema($table_name) {}

    /**
     * Retrieves the columns of the specified table.
     *
     * @param string $table_name    The name of the table whose columns are to be retrieved.
     * @return string[] Column names.
     */
    public function getTableColumns($table_name) {}

    /**
     * Retrieves the unique constraints of the specified table.
     *
     * @param string $table_name    The name of the table whose constraints are to be retrieved.
     * @return string[] Unique constraint names.
     */
    public function getTableUniqueConstraints($table_name) {}

    /**
     * Generates the SQL query to create a specific table.
     * The query holds a condition to run only if the table does not exist yet.
     *
     * @param string $table_name    The name of the table for which the creation SQL is generated.
     * @return string SQL query to create the specified table.
     */
    public function getQueryCreateTable($table_name) {}

    /**
     * Generates one or more SQL queries related to a column creation, according to a given column definition.
     *
     * $def structure:
     * [
     *      'type'             => int(11),
     *      'null'             => false,
     *      'default'          => 0,
     *      'auto_increment'   => false,
     *       'primary'         => false,
     *      'index'            => false
     * ]
     * @param string $table_name    The name of the table to modify.
     * @param string $column_name   The name of the column to add.
     * @param array $def            Array describing the column properties such as type, nullability, default value, etc.
     * @return string SQL query to add a column.
    */
    public function getQueryAddColumn($table_name, $column_name, $def) {}

    /**
     * Generates a SQL query to add an index to a table.
     *
     * @param string $table_name    The name of the table.
     * @param string $column        The name of the column to index.
     * @return string SQL query to add an index.
     */
    public function getQueryAddIndex($table_name, $column) {}

    /**
     * Generates a SQL query to add a composite index to a table.
     *
     * @param string $table_name    The name of the table.
     * @param string[] $columns    Names of the columns included in the composite index.
     * @return string|null SQL query to add an index, or null when the active driver does not implement composite indexes.
     */
    public function getQueryAddCompositeIndex($table_name, $columns) {
    }

    /**
     * Generates a SQL query to add a unique constraint to one or more columns in a table.
     *
     * @param string $table_name        The name of the table.
     * @param string[] $columns         The names of the columns to include in the unique constraint.
     * @return string SQL query to add a unique constraint.
     */
    public function getQueryAddUniqueConstraint($table_name, $columns) {}

    /**
     * Generates a SQL query to add records to a table.
     *
     * @param string $table     The name of the table where records will be added.
     * @param array $fields     Array of field names corresponding to the columns in the table.
     * @param array $values     Array of values to be inserted; each sub-array corresponds to a row.
     * @return string SQL query to add records.
     */
    public function getQueryAddRecords($table, $fields, $values) {}

    /**
     * Generates the initial SQL query used to update columns according to an associative array.
     *
     * Conditions selecting the records to update are appended by `setRecords()`.
     *
     * @param string $table     Name of the table whose records will be updated.
     * @param array $fields     Map of column names to their new values.
     * @return string Initial SQL query used to update records.
     */
    public function getQuerySetRecords($table, $fields) {}
}
